# Dictionary of world currencies with their short codes as keys and full names as values
currency_codes = {
    "USD": "United States Dollar",
    "EUR": "Euro",
    "JPY": "Japanese Yen",
    "GBP": "British Pound Sterling",
    "AUD": "Australian Dollar",
    "CAD": "Canadian Dollar",
    "CHF": "Swiss Franc",
    "CNY": "Chinese Yuan Renminbi",
    "SEK": "Swedish Krona",
    "NZD": "New Zealand Dollar",
    "MXN": "Mexican Peso",
    "SGD": "Singapore Dollar",
    "HKD": "Hong Kong Dollar",
    "NOK": "Norwegian Krone",
    "KRW": "South Korean Won",
    "TRY": "Turkish Lira",
    "INR": "Indian Rupee",
    "BRL": "Brazilian Real",
    "ZAR": "South African Rand",
    "PHP": "Philippine Peso",
    "CZK": "Czech Koruna",
    "IDR": "Indonesian Rupiah",
    "MYR": "Malaysian Ringgit",
    "HUF": "Hungarian Forint",
    "ISK": "Icelandic Krona",
    "HRK": "Croatian Kuna",
    "BGN": "Bulgarian Lev",
    "RON": "Romanian Leu",
    "DKK": "Danish Krone",
    "THB": "Thai Baht",
    "PLN": "Polish Zloty",
    "ILS": "Israeli New Shekel",
    "CLP": "Chilean Peso",
    "PKR": "Pakistani Rupee",
    "BDT": "Bangladeshi Taka",
    "VND": "Vietnamese Dong",
    "ARS": "Argentine Peso",
    "COP": "Colombian Peso",
    "SAR": "Saudi Riyal",
    "AED": "UAE Dirham",
    "QAR": "Qatari Riyal",
    "KWD": "Kuwaiti Dinar",
    "BHD": "Bahraini Dinar",
    "OMR": "Omani Rial",
    "JOD": "Jordanian Dinar",
    "EGP": "Egyptian Pound",
    "NGN": "Nigerian Naira",
    "KES": "Kenyan Shilling",
    "GHS": "Ghanaian Cedi",
    "TZS": "Tanzanian Shilling",
    "UGX": "Ugandan Shilling",
    "ETB": "Ethiopian Birr",
    "ZMW": "Zambian Kwacha",
    "ZWL": "Zimbabwean Dollar",
    "BWP": "Botswana Pula",
    "MUR": "Mauritian Rupee",
    "MVR": "Maldivian Rufiyaa",
    "LKR": "Sri Lankan Rupee",
    "NPR": "Nepalese Rupee",
    "AFN": "Afghan Afghani",
    "IRR": "Iranian Rial",
    "IQD": "Iraqi Dinar",
    "LBP": "Lebanese Pound",
    "SYP": "Syrian Pound",
    "YER": "Yemeni Rial",
    "LYD": "Libyan Dinar",
    "SDG": "Sudanese Pound",
    "SOS": "Somali Shilling",
    "MAD": "Moroccan Dirham",
    "TND": "Tunisian Dinar",
    "DZD": "Algerian Dinar",
    "MKD": "Macedonian Denar",
    "RSD": "Serbian Dinar",
    "GEL": "Georgian Lari",
    "AMD": "Armenian Dram",
    "AZN": "Azerbaijani Manat",
    "KZT": "Kazakhstani Tenge",
    "UZS": "Uzbekistani Som",
    "KGS": "Kyrgyzstani Som",
    "TJS": "Tajikistani Somoni",
    "TMT": "Turkmenistani Manat",
    "MNT": "Mongolian Tugrik",
    "BTN": "Bhutanese Ngultrum",
    "KPW": "North Korean Won",
    "KHR": "Cambodian Riel",
    "LAK": "Laotian Kip",
    "MMK": "Myanmar Kyat",
    "BND": "Brunei Dollar",
    "FJD": "Fiji Dollar",
    "TOP": "Tongan Paʻanga",
    "WST": "Samoan Tala",
    "PGK": "Papua New Guinean Kina",
    "SBD": "Solomon Islands Dollar",
    "VUV": "Vanuatu Vatu",
    "XPF": "New Caledonian CFP Franc",
    "XCD": "East Caribbean Dollar",
    "BMD": "Bermudian Dollar",
    "BSD": "Bahamian Dollar",
    "BBD": "Barbadian Dollar",
    "TTD": "Trinidad and Tobago Dollar",
    "JMD": "Jamaican Dollar",
    "CUP": "Cuban Peso",
    "HTG": "Haitian Gourde",
    "DOP": "Dominican Peso",
    "PAB": "Panamanian Balboa",
    "CRC": "Costa Rican Colon",
    "NIO": "Nicaraguan Cordoba",
    "HNL": "Honduran Lempira",
    "GTQ": "Guatemalan Quetzal",
    "BZD": "Belize Dollar",
    "PYG": "Paraguayan Guarani",
    "UYU": "Uruguayan Peso",
    "BOB": "Bolivian Boliviano",
    "PEN": "Peruvian Sol",
    "SRD": "Surinamese Dollar",
    "VES": "Venezuelan Bolivar",
    "GYD": "Guyana Dollar",
}
