
# reverse_currency_codes.py

currency_codes = {
    'AED': {'name': 'United Arab Emirates Dirham', 'symbol': 'د.إ'},
    'AFN': {'name': 'Afghan Afghani', 'symbol': '؋'},
    'ALL': {'name': 'Albanian Lek', 'symbol': 'L'},
    'AMD': {'name': 'Armenian Dram', 'symbol': '֏'},
    'ANG': {'name': 'Netherlands Antillean Guilder', 'symbol': 'ƒ'},
    'AOA': {'name': 'Angolan Kwanza', 'symbol': 'Kz'},
    'ARS': {'name': 'Argentine Peso', 'symbol': '$'},
    'AUD': {'name': 'Australian Dollar', 'symbol': '$'},
    'AWG': {'name': 'Aruban Florin', 'symbol': 'ƒ'},
    'AZN': {'name': 'Azerbaijani Manat', 'symbol': '₼'},
    'BAM': {'name': 'Bosnia and Herzegovina Convertible Mark', 'symbol': 'KM'},
    'BBD': {'name': 'Barbadian Dollar', 'symbol': '$'},
    'BDT': {'name': 'Bangladeshi Taka', 'symbol': '৳'},
    'BGN': {'name': 'Bulgarian Lev', 'symbol': 'лв'},
    'BHD': {'name': 'Bahraini Dinar', 'symbol': '.د.ب'},
    'BIF': {'name': 'Burundian Franc', 'symbol': 'FBu'},
    'BMD': {'name': 'Bermudian Dollar', 'symbol': '$'},
    'BND': {'name': 'Brunei Dollar', 'symbol': '$'},
    'BOB': {'name': 'Bolivian Boliviano', 'symbol': 'Bs.'},
    'BRL': {'name': 'Brazilian Real', 'symbol': 'R$'},
    'BSD': {'name': 'Bahamian Dollar', 'symbol': '$'},
    'BTN': {'name': 'Bhutanese Ngultrum', 'symbol': 'Nu.'},
    'BWP': {'name': 'Botswana Pula', 'symbol': 'P'},
    'BYN': {'name': 'Belarusian Ruble', 'symbol': 'Br'},
    'BZD': {'name': 'Belize Dollar', 'symbol': 'BZ$'},
    'CAD': {'name': 'Canadian Dollar', 'symbol': '$'},
    'CDF': {'name': 'Congolese Franc', 'symbol': 'FC'},
    'CHF': {'name': 'Swiss Franc', 'symbol': 'CHF'},
    'CLP': {'name': 'Chilean Peso', 'symbol': '$'},
    'CNY': {'name': 'Chinese Yuan', 'symbol': '¥'},
    'COP': {'name': 'Colombian Peso', 'symbol': '$'},
    'CRC': {'name': 'Costa Rican Colón', 'symbol': '₡'},
    'CUP': {'name': 'Cuban Peso', 'symbol': '$'},
    'CVE': {'name': 'Cape Verdean Escudo', 'symbol': '$'},
    'CZK': {'name': 'Czech Koruna', 'symbol': 'Kč'},
    'DJF': {'name': 'Djiboutian Franc', 'symbol': 'Fdj'},
    'DKK': {'name': 'Danish Krone', 'symbol': 'kr'},
    'DOP': {'name': 'Dominican Peso', 'symbol': 'RD$'},
    'DZD': {'name': 'Algerian Dinar', 'symbol': 'دج'},
    'EGP': {'name': 'Egyptian Pound', 'symbol': '£'},
    'ERN': {'name': 'Eritrean Nakfa', 'symbol': 'Nfk'},
    'ETB': {'name': 'Ethiopian Birr', 'symbol': 'Br'},
    'EUR': {'name': 'Euro', 'symbol': '€'},
    'FJD': {'name': 'Fijian Dollar', 'symbol': '$'},
    'FKP': {'name': 'Falkland Islands Pound', 'symbol': '£'},
    'FOK': {'name': 'Faroese Króna', 'symbol': 'kr'},
    'GBP': {'name': 'British Pound', 'symbol': '£'},
    'GEL': {'name': 'Georgian Lari', 'symbol': '₾'},
    'GHS': {'name': 'Ghanaian Cedi', 'symbol': '₵'},
    'GIP': {'name': 'Gibraltar Pound', 'symbol': '£'},
    'GMD': {'name': 'Gambian Dalasi', 'symbol': 'D'},
    'GNF': {'name': 'Guinean Franc', 'symbol': 'FG'},
    'GTQ': {'name': 'Guatemalan Quetzal', 'symbol': 'Q'},
    'GYD': {'name': 'Guyanese Dollar', 'symbol': '$'}
}
